[package]
name = "daberu"
version = "0.1.0"
edition = "2021"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A simple command-line tool for conversing with ChatGPT"
homepage = "https://github.com/sile/daberu"
repository = "https://github.com/sile/daberu"
readme = "README.md"

[dependencies]
clap = { version = "4.3.0", features = ["derive", "env"] }
orfail = "1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
ureq = { version = "2.6.2", features = ["json"] }
