[package]
name = "daberu"
version = "0.2.2"
edition = "2024"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A simple command-line tool for conversing with ChatGPT / Claude"
homepage = "https://github.com/sile/daberu"
repository = "https://github.com/sile/daberu"
readme = "README.md"
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.3.0", features = ["derive", "env"] }
orfail = "1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
ureq = { version = "3", features = ["json"] }
