[package]
name = "daberu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive", "env"] }
orfail = "0.1.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
ureq = { version = "2.6.2", features = ["json"] }